/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLinesRouteImport } from './routes/_authenticated/lines'
import { Route as AuthenticatedResellersRouteImport } from './routes/_authenticated/resellers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLinesRoute = AuthenticatedLinesRouteImport.update({
  id: '/_authenticated/lines',
  path: '/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResellersRoute = AuthenticatedResellersRouteImport.update({
  id: '/_authenticated/resellers',
  path: '/resellers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lines': typeof AuthenticatedLinesRoute
  '/resellers': typeof AuthenticatedResellersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lines': typeof AuthenticatedLinesRoute
  '/resellers': typeof AuthenticatedResellersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/lines': typeof AuthenticatedLinesRoute
  '/_authenticated/resellers': typeof AuthenticatedResellersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lines' | '/resellers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lines' | '/resellers'
  id: '__root__' | '/' | '/_authenticated/lines' | '/_authenticated/resellers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedLinesRoute: typeof AuthenticatedLinesRoute
  AuthenticatedResellersRoute: typeof AuthenticatedResellersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lines': {
      id: '/_authenticated/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof AuthenticatedLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resellers': {
      id: '/_authenticated/resellers'
      path: '/resellers'
      fullPath: '/resellers'
      preLoaderRoute: typeof AuthenticatedResellersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedLinesRoute: AuthenticatedLinesRoute,
  AuthenticatedResellersRoute: AuthenticatedResellersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
