/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetDotphpRouteImport } from './routes/get[.]php'
import { Route as Player_apiDotphpRouteImport } from './routes/player_api[.]php'
import { Route as XmltvDotphpRouteImport } from './routes/xmltv[.]php'
import { Route as ApiPublicGetDotphpRouteImport } from './routes/api/public/get[.]php'
import { Route as ApiPublicPlayer_apiDotphpRouteImport } from './routes/api/public/player_api[.]php'
import { Route as LiveUserPassIdRouteImport } from './routes/live/$user/$pass/$id'
import { Route as MovieUserPassIdRouteImport } from './routes/movie/$user/$pass/$id'
import { Route as SeriesUserPassIdRouteImport } from './routes/series/$user/$pass/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetDotphpRoute = GetDotphpRouteImport.update({
  id: '/get.php',
  path: '/get.php',
  getParentRoute: () => rootRouteImport,
} as any)
const Player_apiDotphpRoute = Player_apiDotphpRouteImport.update({
  id: '/player_api.php',
  path: '/player_api.php',
  getParentRoute: () => rootRouteImport,
} as any)
const XmltvDotphpRoute = XmltvDotphpRouteImport.update({
  id: '/xmltv.php',
  path: '/xmltv.php',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetDotphpRoute = ApiPublicGetDotphpRouteImport.update({
  id: '/api/public/get.php',
  path: '/api/public/get.php',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayer_apiDotphpRoute =
  ApiPublicPlayer_apiDotphpRouteImport.update({
    id: '/api/public/player_api.php',
    path: '/api/public/player_api.php',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiveUserPassIdRoute = LiveUserPassIdRouteImport.update({
  id: '/live/$user/$pass/$id',
  path: '/live/$user/$pass/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieUserPassIdRoute = MovieUserPassIdRouteImport.update({
  id: '/movie/$user/$pass/$id',
  path: '/movie/$user/$pass/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesUserPassIdRoute = SeriesUserPassIdRouteImport.update({
  id: '/series/$user/$pass/$id',
  path: '/series/$user/$pass/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get.php': typeof GetDotphpRoute
  '/player_api.php': typeof Player_apiDotphpRoute
  '/xmltv.php': typeof XmltvDotphpRoute
  '/api/public/get.php': typeof ApiPublicGetDotphpRoute
  '/api/public/player_api.php': typeof ApiPublicPlayer_apiDotphpRoute
  '/live/$user/$pass/$id': typeof LiveUserPassIdRoute
  '/movie/$user/$pass/$id': typeof MovieUserPassIdRoute
  '/series/$user/$pass/$id': typeof SeriesUserPassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get.php': typeof GetDotphpRoute
  '/player_api.php': typeof Player_apiDotphpRoute
  '/xmltv.php': typeof XmltvDotphpRoute
  '/api/public/get.php': typeof ApiPublicGetDotphpRoute
  '/api/public/player_api.php': typeof ApiPublicPlayer_apiDotphpRoute
  '/live/$user/$pass/$id': typeof LiveUserPassIdRoute
  '/movie/$user/$pass/$id': typeof MovieUserPassIdRoute
  '/series/$user/$pass/$id': typeof SeriesUserPassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get.php': typeof GetDotphpRoute
  '/player_api.php': typeof Player_apiDotphpRoute
  '/xmltv.php': typeof XmltvDotphpRoute
  '/api/public/get.php': typeof ApiPublicGetDotphpRoute
  '/api/public/player_api.php': typeof ApiPublicPlayer_apiDotphpRoute
  '/live/$user/$pass/$id': typeof LiveUserPassIdRoute
  '/movie/$user/$pass/$id': typeof MovieUserPassIdRoute
  '/series/$user/$pass/$id': typeof SeriesUserPassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get.php'
    | '/player_api.php'
    | '/xmltv.php'
    | '/api/public/get.php'
    | '/api/public/player_api.php'
    | '/live/$user/$pass/$id'
    | '/movie/$user/$pass/$id'
    | '/series/$user/$pass/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get.php'
    | '/player_api.php'
    | '/xmltv.php'
    | '/api/public/get.php'
    | '/api/public/player_api.php'
    | '/live/$user/$pass/$id'
    | '/movie/$user/$pass/$id'
    | '/series/$user/$pass/$id'
  id:
    | '__root__'
    | '/'
    | '/get.php'
    | '/player_api.php'
    | '/xmltv.php'
    | '/api/public/get.php'
    | '/api/public/player_api.php'
    | '/live/$user/$pass/$id'
    | '/movie/$user/$pass/$id'
    | '/series/$user/$pass/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetDotphpRoute: typeof GetDotphpRoute
  Player_apiDotphpRoute: typeof Player_apiDotphpRoute
  XmltvDotphpRoute: typeof XmltvDotphpRoute
  ApiPublicGetDotphpRoute: typeof ApiPublicGetDotphpRoute
  ApiPublicPlayer_apiDotphpRoute: typeof ApiPublicPlayer_apiDotphpRoute
  LiveUserPassIdRoute: typeof LiveUserPassIdRoute
  MovieUserPassIdRoute: typeof MovieUserPassIdRoute
  SeriesUserPassIdRoute: typeof SeriesUserPassIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get.php': {
      id: '/get.php'
      path: '/get.php'
      fullPath: '/get.php'
      preLoaderRoute: typeof GetDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player_api.php': {
      id: '/player_api.php'
      path: '/player_api.php'
      fullPath: '/player_api.php'
      preLoaderRoute: typeof Player_apiDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xmltv.php': {
      id: '/xmltv.php'
      path: '/xmltv.php'
      fullPath: '/xmltv.php'
      preLoaderRoute: typeof XmltvDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get.php': {
      id: '/api/public/get.php'
      path: '/api/public/get.php'
      fullPath: '/api/public/get.php'
      preLoaderRoute: typeof ApiPublicGetDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player_api.php': {
      id: '/api/public/player_api.php'
      path: '/api/public/player_api.php'
      fullPath: '/api/public/player_api.php'
      preLoaderRoute: typeof ApiPublicPlayer_apiDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$user/$pass/$id': {
      id: '/live/$user/$pass/$id'
      path: '/live/$user/$pass/$id'
      fullPath: '/live/$user/$pass/$id'
      preLoaderRoute: typeof LiveUserPassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$user/$pass/$id': {
      id: '/movie/$user/$pass/$id'
      path: '/movie/$user/$pass/$id'
      fullPath: '/movie/$user/$pass/$id'
      preLoaderRoute: typeof MovieUserPassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$user/$pass/$id': {
      id: '/series/$user/$pass/$id'
      path: '/series/$user/$pass/$id'
      fullPath: '/series/$user/$pass/$id'
      preLoaderRoute: typeof SeriesUserPassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetDotphpRoute: GetDotphpRoute,
  Player_apiDotphpRoute: Player_apiDotphpRoute,
  XmltvDotphpRoute: XmltvDotphpRoute,
  ApiPublicGetDotphpRoute: ApiPublicGetDotphpRoute,
  ApiPublicPlayer_apiDotphpRoute: ApiPublicPlayer_apiDotphpRoute,
  LiveUserPassIdRoute: LiveUserPassIdRoute,
  MovieUserPassIdRoute: MovieUserPassIdRoute,
  SeriesUserPassIdRoute: SeriesUserPassIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
